export const skillset = [
    "HTML5",
    "RWD",
    "Accessibility and Semantics",
    "BEM notation",
    "Markdown",
    "npm",
    "CSS3",
    "CSS Grid",
    "CSS Flexbox",
    "JavaScript ES6",
    "Local Storage",
    "Immutability",
    "React",
    "Custom Hooks",
    "Redux and toolkit",
    "Redux Saga",
    "React- Router",
    "Axios",
    "Git",
    "Teamwork",
    "Customer Service"
];